### ISSUE TITLE
Mod catalogue [LEGACY]

### ISSUE THREAD

**Issue by Talark-Systems** [Element-0/MinimalModTemplate#1]
For every mod that somebody makes please post a comment for this in the following format (please only comment when mod works and not when you make the repository):
This will help us catalog all the mods that have been made, however, this is also entirely optional.
~~~comment
Name: <modName>
Description: <modDescription>
Usage: <Small documentation>
Link: <GitHub link to repository>
~~~

**Comment by Weissnix4711** [comment]
Name: ExampleMod
Description: This is a test
Usage: none
Link: http://www.example.com

**Comment by Weissnix4711** [comment]
Can we remove this now that the [forum](https://elementzero.flarum.cloud/) page exists?

**Comment by Talark-Systems** [comment]
Sure! However, I'm keeping the other one open until the forum and the other one match:

The other one: https://github.com/Element-0/ModTemplate/issues/1

**Comment by Bluebotlaboratories** [comment]
I am, however, unable to unpin this...
